import { BookRecord } from "../types";

export const SAMPLE_BOOKS: BookRecord[] = [
  {
    id: "sample-1",
    biblionumber: "20101",
    title: "Vidas de Professores",
    author: "António Nóvoa",
    isbn: "9789720341044",
    publicationyear: "1992",
    itemcallnumber: "371.12 NOV VID",
    status: "pending",
  },
  {
    id: "sample-2",
    biblionumber: "20102",
    title: "Curriculum Development",
    author: "Wiles, Jon; Bondi, Joseph",
    isbn: "9780131932357",
    publicationyear: "1984",
    itemcallnumber: "371.21 WIL CUR",
    status: "pending",
  },
  {
    id: "sample-3",
    biblionumber: "20103",
    title: "Formação contínua de professores ao serviço do desenvolvimento profissional docente",
    author: "Maria Prazeres Casanova",
    isbn: "9789898555120",
    publicationyear: "2011",
    itemcallnumber: "371.12 CAS FOR",
    status: "pending",
  },
  {
    id: "sample-4",
    biblionumber: "20104",
    title: "A relação escola-família",
    author: "Andreia Coxinho",
    isbn: "9789897300059",
    publicationyear: "2018",
    itemcallnumber: "37.018 COX REL",
    status: "pending",
  },
  {
    id: "sample-5",
    biblionumber: "20105",
    title: "Democracy and Education: An Introduction to the Philosophy of Education",
    author: "John Dewey",
    isbn: "9780486433998",
    publicationyear: "1916",
    itemcallnumber: "37.01 DEW DEM",
    status: "pending",
  },
  {
    id: "sample-6",
    biblionumber: "20106",
    title: "A Escola: o lugar onde os professores aprendem",
    author: "Rui Canário",
    isbn: "9789729661440",
    publicationyear: "1999",
    itemcallnumber: "371.12 CAN ESC",
    status: "pending",
  }
];
